In [1]:
import pdftables_api

In [2]:
c = pdftables_api.Client('tdcthtpa2b3z', timeout=(60, 3600))
c.xlsx('Auctresults-1872.pdf', 'Ghana.xlsx')

In [3]:
import pandas as pd

In [27]:
df = pd.read_excel("Ghana.xlsx")

In [28]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,O F GH,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN
1,NaN,NK,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ES,NaN,NaN,T. 1 9 5 7,NaN,NaN,NaN,NaN
3,NaN,BANK OF GHANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NOTICE TO BANKS AND PUBLIC NO. BG/FMD/2023/70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,GOVERNMENT OF GHANA SECURITIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.,RESULTS OF TENDER 1872 HELD ON 13TH OCTOBER 20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,TH,NaN,NaN,NaN,NaN
8,NaN,GHANA SECURITIES TO BE ISSUED ON 16,NaN,NaN,NaN,OCTOBER 2023.,NaN,NaN,NaN
9,ISIN,SECURITIES,BIDS (AMT),BIDS (AMT),RANGE OF,NaN,NaN,WEIGHTED AVG.,NaN
10,NaN,NaN,TENDERED,NaN,NaN,BID RATES ALLOTTED IN FULL,NaN,NaN,NaN
11,NaN,NaN,NaN,ACCEPTED,BID RATES,NaN,NaN,RATES FOR THE,NaN
12,NaN,NaN,GH¢ (M),GH¢ (M),(% P.A.),NaN,(%P.A.),WEEK 16TH – 20TH OCT,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023 (%P.A.),NaN
14,NaN,NaN,NaN,NaN,NaN,Discount,Interest,Discount,Interest
15,NaN,NaN,NaN,NaN,NaN,Rate,Rate,Rate,Rate
16,GHGGOG072273,91 Day Bill,"GH¢2,296.21","GH¢2,102.58",26.9000-27.9070,26.9000-27.6500,28.8395-29.7032,27.4589,29.4828
17,GHGGOG072281,182 Day Bill,GH¢324.09,GH¢324.03,26.4642-27.4374,26.4642-27.2884,30.5000-31.6000,27.1585,31.4259
18,GHGGOG072299,364 Day Bill,GH¢183.66,GH¢183.66,24.5283-25.1000,24.5283-25.1000,32.5000-33.5114,24.9329,33.2142
19,"TARGET FOR 91, 182 AND 364-DAY T/BILLS: GH¢2,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,TH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2. SUMMARY OF TENDER 1871 HELD ON 6 OCTOBER 2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,SECURITIES,NaN,TOTAL AMOUNT TENDERED,NaN,NaN,TOTAL AMOUNT SOLD,NaN,NaN,NaN
23,"91, 182 AND 364 -DAY T/BILLS",NaN,"GH¢ 2,626.30 Million",NaN,NaN,"GH¢ 2,576.60 Million",NaN,NaN,NaN
24,GHGGOG059817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,3.TARGET FOR TENDER 1873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,SECURITIES AMOUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"91,182 AND 364 -DAY T/BILLS GH¢ 2,282.00 Million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,I),The GOG Securities Wholesale Auction is opened...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,II),All Primary Dealers are obliged to act as mark...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,III),The Investing Public interested in purchasing ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,(Ghana Fixed Income Market) through Depository...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,.................................................,NaN,NaN,NaN,NaN,NaN
33,(SGD.),NaN,NaN,.................................................,NaN,NaN,NaN,NaN,NaN
34,SANDRA THOMPSON (MS),NaN,NaN,.................................................,NaN,NaN,NaN,NaN,NaN
35,THE SECRETARY,NaN,NaN,.....................1...3TH... .OCTOBER 2023,NaN,NaN,NaN,NaN,NaN

In [29]:
new_df = df.iloc[16:19, [0, 1, 2, 3, 4, 5, 6, 7, 8]]

# Renommez les colonnes du nouveau DataFrame
new_df.columns = ['ISIN', 'SECURITIES', 'BIDS (AMT) TENDERED GH¢ (M)', 'BIDS (AMT) ACCEPTED GH¢ (M)', 'Range', 'Discount', 'Interest', 'Discount Rate', 'Interest Rate']

# Affichez le nouveau DataFrame
new_df

,ISIN,SECURITIES,BIDS (AMT) TENDERED GH¢ (M),BIDS (AMT) ACCEPTED GH¢ (M),Range,Discount,Interest,Discount Rate,Interest Rate
16,GHGGOG072273,91 Day Bill,"GH¢2,296.21","GH¢2,102.58",26.9000-27.9070,26.9000-27.6500,28.8395-29.7032,27.4589,29.4828
17,GHGGOG072281,182 Day Bill,GH¢324.09,GH¢324.03,26.4642-27.4374,26.4642-27.2884,30.5000-31.6000,27.1585,31.4259
18,GHGGOG072299,364 Day Bill,GH¢183.66,GH¢183.66,24.5283-25.1000,24.5283-25.1000,32.5000-33.5114,24.9329,33.2142

In [30]:
columns1 = ['BIDS (AMT) TENDERED GH¢ (M)', 'BIDS (AMT) ACCEPTED GH¢ (M)']

for column in columns1:
    new_df[column] = new_df[column].str.replace('GH¢', '', regex=True)

In [31]:
# Supprimez les virgules et convertissez en float
for column in columns1:
    new_df[column] = pd.to_numeric(new_df[column].str.replace(',', ''), errors='coerce')

In [35]:
# Liste des colonnes à multiplier par 1,000,000
columns_to_multiply = ['BIDS (AMT) TENDERED GH¢ (M)', 'BIDS (AMT) ACCEPTED GH¢ (M)']

# Multipliez les colonnes par 1,000,000
new_df[columns_to_multiply] = new_df[columns_to_multiply] * 1000000

In [33]:
# Liste des colonnes à convertir en nombres flottants
columns_to_convert = ['Discount Rate', 'Interest Rate']

# Convertir les colonnes en nombres flottants
new_df[columns_to_convert] = new_df[columns_to_convert].apply(lambda x: pd.to_numeric(x, errors='coerce'))

In [36]:
new_df

,ISIN,SECURITIES,BIDS (AMT) TENDERED GH¢ (M),BIDS (AMT) ACCEPTED GH¢ (M),Range,Discount,Interest,Discount Rate,Interest Rate
16,GHGGOG072273,91 Day Bill,2.296210e+09,2.102580e+09,26.9000-27.9070,26.9000-27.6500,28.8395-29.7032,27.4589,29.4828
17,GHGGOG072281,182 Day Bill,3.240900e+08,3.240300e+08,26.4642-27.4374,26.4642-27.2884,30.5000-31.6000,27.1585,31.4259
18,GHGGOG072299,364 Day Bill,1.836600e+08,1.836600e+08,24.5283-25.1000,24.5283-25.1000,32.5000-33.5114,24.9329,33.2142

In [37]:
# Spécifiez le nom du fichier Excel de destination
nom_fichier_excel = 'Ghana_scrap.xlsx'

# Exportez le DataFrame vers Excel
new_df.to_excel(nom_fichier_excel, index=True)